apiVersion: v1
kind: Template
labels:
  app: employee-rostering
metadata:
  annotations:
    description: Employee Rostering with OptaPlanner on OpenShift
    iconClass: icon-java
    tags: optaplanner,jboss
  name: employee-rostering-builds
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: employee-rostering
  spec:
    tags:
      - name: latest
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: employee-rostering
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: employee-rostering:latest
    source:
      git:
        ref: ${GIT_REF}
        uri: ${GIT_URI}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: wildfly:11.0
          namespace: openshift
      type: Source
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
    runPolicy: Serial
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    generation: 1
    labels:
      app: employee-rostering
    name: employee-rostering
  spec:
    replicas: 1
    selector:
      app: employee-rostering
      deploymentconfig: employee-rostering
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: employee-rostering
          deploymentconfig: employee-rostering
      spec:
        containers:
        - image: employee-rostering
          imagePullPolicy: Always
          name: employee-rostering
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - employee-rostering
        from:
          kind: ImageStreamTag
          name: employee-rostering:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    name: employee-rostering
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: employee-rostering
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    name: employee-rostering
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: employee-rostering
      weight: 100
parameters:
- description: Git source URI for application
  displayName: Git source repository
  name: GIT_URI
  required: true
  value: https://github.com/ge0ffrey/optashift-employee-rostering
- description: Git branch/tag reference
  displayName: Git branch/tag reference
  name: GIT_REF
  required: true
  value: master
