name: CI

on: [push, pull_request]

jobs:
  os-java:
    name: OS x Java
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [8, 11]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Maven
        run: mvn -B install -Prun-code-coverage -Dintegration-tests=true
      - name: Run SonarCloud analysis
        run: mvn -B sonar:sonar -Psonarcloud-analysis
      # check that git working tree is clean after running npm install via a frontend-maven-plugin
      # the git command returns 1 and fails the build if there are any uncommitted changes
      - name: Check for clean working tree
        run: git diff HEAD --exit-code

  # Early feedback on a compatibility with the newest Java version.
  # TODO: update each time a new major Java version is released.
  latest-jdk:
    name: Java 14
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Build with Maven
        run: mvn -B install -Dintegration-tests=true
